#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: 明月有色
 * Date: 2018/1/18
 * Time: 18:03
 */

require __DIR__.'/bootstrap/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';

$console = new \Symfony\Component\Console\Application('Universe','1.0');

$console->add(new \Universe\Console\ServerStartCommand($app));
$console->add(new \Universe\Console\ServerStopCommand());
$console->add(new \Universe\Console\ServerReloadCommand());

$console->run();
