#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: 明月有色
 * Date: 2018/1/18
 * Time: 18:03
 */

require __DIR__.'/bootstrap/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';

$console = new \Symfony\Component\Console\Application('Universe','1.0');

// httpServer
$console->add(new \Universe\Console\Http\ServerStartCommand($app));
$console->add(new \Universe\Console\Http\ServerStopCommand());
$console->add(new \Universe\Console\Http\ServerReloadCommand());

//webSocketServer
$console->add(new \Universe\Console\WebSocket\ServerStartCommand($app));
$console->add(new \Universe\Console\WebSocket\ServerStopCommand());
$console->add(new \Universe\Console\WebSocket\ServerReloadCommand());

$console->run();
